# Build the manager binary
FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/
COPY pkg/ pkg/
COPY vendor/ vendor/
COPY bindata/manifests/ bindata/manifests/

# Build
RUN CGO_ENABLED=0 GO111MODULE=on go build -a -mod=vendor -o manager main.go

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9
WORKDIR /
COPY --from=builder /workspace/manager .
COPY --from=builder /workspace/bindata/manifests /bindata/manifests

ENTRYPOINT ["/manager"]
